class OptionsList {
  static const List<String> hobbys = [
    "📚 Reading",
    "✍️ Writing",
    "🎨 Drawing",
    "🖌️ Painting",
    "📷 Photography",
    "🎸 Playing Guitar",
    "🎹 Playing Piano",
    "🎤 Singing",
    "💃 Dancing",
    "🍳 Cooking",
    "🎂 Baking",
    "🌱 Gardening",
    "⛰️ Hiking",
    "🏃 Running",
    "🚴 Cycling",
    "🏊 Swimming",
    "🎣 Fishing",
    "⛺ Camping",
    "♟️ Chess",
    "🎮 Playing Video Games",
    "🎬 Watching Movies",
    "🎥 Watching Anime",
    "🛠️ DIY Projects",
    "🧶 Knitting",
    "🧘 Yoga",
    "🕉️ Meditation",
    "🖋️ Calligraphy",
    "🔨 Woodworking",
    "🛹 Skateboarding",
    "🏄 Surfing",
    "🧗 Rock Climbing",
    "✈️ Traveling",
    "🌍 Learning Languages",
    "🔭 Astronomy",
    "🐎 Horseback Riding",
    "💻 Coding"
  ];
  static const List<String> personalityTypes = [
    "🤝 Extrovert",
    "🤫 Introvert",
    "🤔 Thinker",
    "❤️ Feeler",
    "🎯 Perfectionist",
    "🌍 Idealist",
    "📅 Planner",
    "🎨 Creative",
    "🧠 Analytical",
    "⚡ Spontaneous",
    "📢 Leader",
    "👥 Team Player",
    "🎭 Expressive",
    "😌 Calm",
    "🔍 Curious",
    "🧐 Observant",
    "🎉 Enthusiastic",
    "🛠️ Problem Solver",
    "🧩 Logical",
    "🤩 Optimist",
    "🌧️ Pessimist",
    "⚖️ Realist",
    "🤹‍♂️ Adaptable",
    "🕵️‍♂️ Mysterious",
    "🦉 Wise",
    "🌟 Dreamer",
    "🦾 Determined",
    "🤗 Empathetic",
    "👓 Intellectual",
    "🦸‍♂️ Adventurous",
    "🎯 Goal-Oriented",
    "🚀 Ambitious",
    "🤝 Diplomatic",
    "🌊 Free-Spirited",
    "🛡️ Protective",
    "🔥 Passionate",
    "😎 Confident",
    "🤯 Deep Thinker",
    "💬 Communicative",
    "🎭 Dramatic"
  ];
  static const List<String> music = [
    "🎸 Rock",
    "🎤 Pop",
    "🎷 Jazz",
    "🎻 Classical",
    "🎧 Hip-Hop",
    "🎵 Blues",
    "🇯🇲 Reggae",
    "🤠 Country",
    "🎶 Electronic",
    "🪕 Folk",
    "🤘 Metal",
    "🎼 R&B",
    "💖 Soul",
    "🕺 Funk",
    "🙏 Gospel",
    "🎸 Punk",
    "🌎 Latin",
    "🎛️ Techno",
    "🏠 House",
    "🎎 K-Pop",
    "🔊 EDM",
    "🎚️ Dubstep",
    "🎵 Trance",
    "🎧 Drum & Bass",
    "💿 Disco",
    "🎼 Opera",
    "🪘 Afrobeat",
    "🥁 Samba",
    "🎺 Ska",
    "🎭 Musical",
    "🛕 Indian Classical",
    "🕌 Arabic",
    "🌅 Chillout",
    "🔥 Trap",
    "🎹 Synthwave",
    "📻 Lo-Fi",
    "🎭 Tango",
    "🎶 Bossa Nova",
    "🎙️ Acapella",
    "🇨🇳 C-Pop",
    "🇷🇺 Russian Pop",
    "🎻 Celtic",
    "🎸 Grunge"
  ];
}
