// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb1mpmWBRd9UuXkrQVjDDgJWKYSqqPCzk',
    appId: '1:208327738954:web:56dc1685e14e57cd7548b3',
    messagingSenderId: '208327738954',
    projectId: 'face-suggets-project',
    authDomain: 'face-suggets-project.firebaseapp.com',
    storageBucket: 'face-suggets-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBejrKsdhcEXkTgPAoVOLv0tKCxARxVn_I',
    appId: '1:208327738954:android:368025d0e83e2fbe7548b3',
    messagingSenderId: '208327738954',
    projectId: 'face-suggets-project',
    storageBucket: 'face-suggets-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZEn6ajgCqIZKCo_1tbWjB9uz3rgHWUc',
    appId: '1:208327738954:ios:8ce74a98ca5b8f4c7548b3',
    messagingSenderId: '208327738954',
    projectId: 'face-suggets-project',
    storageBucket: 'face-suggets-project.firebasestorage.app',
    iosBundleId: 'com.example.xxx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpZEn6ajgCqIZKCo_1tbWjB9uz3rgHWUc',
    appId: '1:208327738954:ios:8ce74a98ca5b8f4c7548b3',
    messagingSenderId: '208327738954',
    projectId: 'face-suggets-project',
    storageBucket: 'face-suggets-project.firebasestorage.app',
    iosBundleId: 'com.example.xxx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb1mpmWBRd9UuXkrQVjDDgJWKYSqqPCzk',
    appId: '1:208327738954:web:2a65372f82fa4c067548b3',
    messagingSenderId: '208327738954',
    projectId: 'face-suggets-project',
    authDomain: 'face-suggets-project.firebaseapp.com',
    storageBucket: 'face-suggets-project.firebasestorage.app',
  );
}
